version: '3.3'

services:
  api:
    image: node:14
    container_name: files
    working_dir: /app
    ports:
      - '9002:9002'
    volumes:
      - .:/app
    command: bash -c "npm install && npm start"
